/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_LWSTEST_TEST_PB_H_INCLUDED
#define PB_LWSTEST_TEST_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _lwstest_Message {
    uint64_t time;
    pb_callback_t message;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:lwstest_Message) */
} lwstest_Message;


/* Initializer values for message structs */
#define lwstest_Message_init_default             {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lwstest_Message_init_zero                {0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define lwstest_Message_time_tag                 1
#define lwstest_Message_message_tag              2
#define lwstest_Message_data_tag                 3

/* Struct field encoding specification for nanopb */
#define lwstest_Message_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT64, time, 1) \
X(a, CALLBACK, SINGULAR, STRING, message, 2) \
X(a, CALLBACK, SINGULAR, BYTES, data, 3)
#define lwstest_Message_CALLBACK pb_default_field_callback
#define lwstest_Message_DEFAULT NULL

extern const pb_msgdesc_t lwstest_Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define lwstest_Message_fields &lwstest_Message_msg

/* Maximum encoded size of messages (where known) */
/* lwstest_Message_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
