/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Fri Apr 27 10:22:23 2018. */

#include "test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t lwstest_Message_fields[4] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, lwstest_Message, time, time, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, lwstest_Message, message, time, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, lwstest_Message, data, message, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
