/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9-dev at Fri Apr 27 10:22:23 2018. */

#ifndef PB_LWSTEST_TEST_PB_H_INCLUDED
#define PB_LWSTEST_TEST_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _lwstest_Message {
    uint64_t time;
    pb_callback_t message;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:lwstest_Message) */
} lwstest_Message;

/* Default values for struct fields */

/* Initializer values for message structs */
#define lwstest_Message_init_default             {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define lwstest_Message_init_zero                {0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define lwstest_Message_time_tag                 1
#define lwstest_Message_message_tag              2
#define lwstest_Message_data_tag                 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t lwstest_Message_fields[4];

/* Maximum encoded size of messages (where known) */
/* lwstest_Message_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TEST_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
